/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./../layouts/components/article-list/index.vue')['default']
    BhButton: typeof import('./../components/bh-button/index.vue')['default']
    BhPaginator: typeof import('./../components/bh-paginator/index.vue')['default']
    BhTooltip: typeof import('./../components/bh-tooltip/index.vue')['default']
    Bottombar: typeof import('./../layouts/components/bottombar/index.vue')['default']
    BottomBar: typeof import('./../layouts/components/bottom-bar/index.vue')['default']
    Default: typeof import('./../layouts/default.vue')['default']
    IRegularBrightness: typeof import('~icons/regular/brightness')['default']
    IRegularChevronLeft: typeof import('~icons/regular/chevron-left')['default']
    IRegularChevronRight: typeof import('~icons/regular/chevron-right')['default']
    IRegularChevronsLeft: typeof import('~icons/regular/chevrons-left')['default']
    IRegularChevronsRight: typeof import('~icons/regular/chevrons-right')['default']
    IRegularGear: typeof import('~icons/regular/gear')['default']
    IRegularMoonStars: typeof import('~icons/regular/moon-stars')['default']
    IRegularRightToBracket: typeof import('~icons/regular/right-to-bracket')['default']
    Loading: typeof import('./../layouts/components/loading/index.vue')['default']
    Navbar: typeof import('./../layouts/components/navbar/index.vue')['default']
    NavBar: typeof import('./../layouts/components/nav-bar/index.vue')['default']
    PaginatorButton: typeof import('./../components/bh-paginator/paginator-button.vue')['default']
    PaginatorButtonGroup: typeof import('./../components/bh-paginator/paginator-button-group.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipContainer: typeof import('./../components/bh-tooltip/tooltip-container.vue')['default']
  }
}
