/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./../layouts/admin.vue')['default']
    ArticleCard: typeof import('./../layouts/components/article-list/article-card.vue')['default']
    ArticleDirectory: typeof import('./../layouts/components/article-directory/index.vue')['default']
    ArticleList: typeof import('./../layouts/components/article-list/index.vue')['default']
    Background: typeof import('./../layouts/components/background/index.vue')['default']
    BhButton: typeof import('./../components/bh-button/index.vue')['default']
    BhEmpty: typeof import('./../components/bh-empty/index.vue')['default']
    BhGallery: typeof import('./../components/bh-gallery/index.vue')['default']
    BhInput: typeof import('./../components/bh-input/index.vue')['default']
    BhNotFound: typeof import('./../components/bh-not-found/index.vue')['default']
    BhPaginator: typeof import('./../components/bh-paginator/index.vue')['default']
    BhSkeleton: typeof import('./../components/bh-skeleton/index.vue')['default']
    BhTextarea: typeof import('./../components/bh-textarea/index.vue')['default']
    BhToast: typeof import('./../components/bh-toast/index.vue')['default']
    BhTooltip: typeof import('./../components/bh-tooltip/index.vue')['default']
    Blog: typeof import('./../layouts/blog.vue')['default']
    BottomBar: typeof import('./../layouts/components/bottom-bar/index.vue')['default']
    CommentBox: typeof import('./../layouts/components/comment-box/index.vue')['default']
    CommentContent: typeof import('./../layouts/components/comment-box/comment-content.vue')['default']
    CommentSender: typeof import('./../layouts/components/comment-box/comment-sender.vue')['default']
    IBrandsBilibili: typeof import('~icons/brands/bilibili')['default']
    IBrandsGithub: typeof import('~icons/brands/github')['default']
    IRegularBrightness: typeof import('~icons/regular/brightness')['default']
    IRegularCalendarLines: typeof import('~icons/regular/calendar-lines')['default']
    IRegularCalendarLinesPen: typeof import('~icons/regular/calendar-lines-pen')['default']
    IRegularChevronLeft: typeof import('~icons/regular/chevron-left')['default']
    IRegularChevronRight: typeof import('~icons/regular/chevron-right')['default']
    IRegularChevronsLeft: typeof import('~icons/regular/chevrons-left')['default']
    IRegularChevronsRight: typeof import('~icons/regular/chevrons-right')['default']
    IRegularCircleCheck: typeof import('~icons/regular/circle-check')['default']
    IRegularEnvelope: typeof import('~icons/regular/envelope')['default']
    IRegularEye: typeof import('~icons/regular/eye')['default']
    IRegularFolder: typeof import('~icons/regular/folder')['default']
    IRegularGear: typeof import('~icons/regular/gear')['default']
    IRegularImage: typeof import('~icons/regular/image')['default']
    IRegularLink: typeof import('~icons/regular/link')['default']
    IRegularList: typeof import('~icons/regular/list')['default']
    IRegularLock: typeof import('~icons/regular/lock')['default']
    IRegularMoonStars: typeof import('~icons/regular/moon-stars')['default']
    IRegularRightToBracket: typeof import('~icons/regular/right-to-bracket')['default']
    IRegularSpinnerThird: typeof import('~icons/regular/spinner-third')['default']
    IRegularTag: typeof import('~icons/regular/tag')['default']
    IRegularUser: typeof import('~icons/regular/user')['default']
    ISolidFolderClosed: typeof import('~icons/solid/folder-closed')['default']
    ISolidXmark: typeof import('~icons/solid/xmark')['default']
    Loading: typeof import('./../layouts/components/loading/index.vue')['default']
    NavBar: typeof import('./../layouts/components/nav-bar/index.vue')['default']
    PaginatorButton: typeof import('./../components/bh-paginator/paginator-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastContainer: typeof import('./../components/bh-toast/toast-container.vue')['default']
    TooltipContainer: typeof import('./../components/bh-tooltip/tooltip-container.vue')['default']
  }
  export interface ComponentCustomProperties {
    vTooltip: typeof import('@/utils/tooltip')['vTooltip']
  }
}
