/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-articles': RouteRecordInfo<'admin-articles', '/admin/articles', Record<never, never>, Record<never, never>>,
    'admin-articles-write': RouteRecordInfo<'admin-articles-write', '/admin/articles/write', Record<never, never>, Record<never, never>>,
    'admin-articles-update': RouteRecordInfo<'admin-articles-update', '/admin/articles/write/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-categories': RouteRecordInfo<'admin-categories', '/admin/categories', Record<never, never>, Record<never, never>>,
    'admin-comments': RouteRecordInfo<'admin-comments', '/admin/comments', Record<never, never>, Record<never, never>>,
    'admin-friends': RouteRecordInfo<'admin-friends', '/admin/friends', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/admin/login', Record<never, never>, Record<never, never>>,
    'admin-roles': RouteRecordInfo<'admin-roles', '/admin/roles', Record<never, never>, Record<never, never>>,
    'admin-tags': RouteRecordInfo<'admin-tags', '/admin/tags', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'article-detail': RouteRecordInfo<'article-detail', '/articles/:id(\d+)', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'categories': RouteRecordInfo<'categories', '/categories', Record<never, never>, Record<never, never>>,
    'category-articles': RouteRecordInfo<'category-articles', '/categories/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    'friends': RouteRecordInfo<'friends', '/friends', Record<never, never>, Record<never, never>>,
    'tags': RouteRecordInfo<'tags', '/tags', Record<never, never>, Record<never, never>>,
    'tag-articles': RouteRecordInfo<'tag-articles', '/tags/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
  }
}
